import { VideoEditorFormat } from "./types/VideoEditingFormat";
import { InputFiles } from "./types/InputFiles";

/**
 * Return all the inputs as a part of ffmpeg command.
 * @param inputs
 */
export function parseInputs({ schema }: { schema: VideoEditorFormat }): {
  command: string;
  inputFiles: InputFiles;
} {
  let inputsCommand = "";
  const inputFiles: InputFiles = [];

  for (const [trackName, track] of Object.entries(schema.tracks)) {
    for (const clip of track.clips) {
      const { source, clipType, name, sourceStartOffset, duration } = clip;
      const { tempDir } = schema.output;

      // Only video clips need preprocessing and input files
      // Text clips are generated by drawtext filter
      if (clipType === "video") {
        inputsCommand += `-i ${tempDir}/${name}.mp4 \\\n`;
        inputFiles.push({
          file: `${name}_tmp.mp4`,
          name: `${name}`,
        });
      }
      // Skip text, audio, and image clips here - they're handled differently
    }
  }

  for (const [inputName, input] of Object.entries(schema.inputs)) {
    // Skip video inputs (handled in clips) and text inputs (generated by drawtext filter)
    if (input.type === "video" || input.type === "text") continue;

    inputsCommand += `-i ${input.file} \\\n`;
    inputFiles.push({
      name: inputName,
      file: input.file,
    });
  }

  return {
    command: inputsCommand,
    inputFiles,
  };
}
